/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.fudan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import edu.fudan.struts.action.BaseAction;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2014
 * 
 * XDoclet definition:
 * @struts.form name="getResultForm"
 */
public class GetResultForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** result property */
	private String result;
	private String moduleId;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the result.
	 * @return String
	 */
	public String getResult() {
		return result;
	}

	/** 
	 * Set the result.
	 * @param result The result to set
	 */
	public void setResult(String result) {
		this.result = result;
	}

	public String getModuleId() {
		return moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}
}