/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.fudan.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 05-25-2014
 * 
 * XDoclet definition:
 * @struts.form name="queryModuleForm"
 */
public class QueryModuleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** queryId property */
	private String queryId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the queryId.
	 * @return String
	 */
	public String getQueryId() {
		return queryId;
	}

	/** 
	 * Set the queryId.
	 * @param queryId The queryId to set
	 */
	public void setQueryId(String queryId) {
		this.queryId = queryId;
	}
}