/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.fudan.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import edu.fudan.service.QueryInputService;
import edu.fudan.service.QueryModuleResultService;
import edu.fudan.struts.form.GetResultForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2014
 * 
 * XDoclet definition:
 * @struts.action path="/getResult" name="getResultForm" input="/getResult.jsp" scope="request" validate="true"
 */
public class GetResultAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetResultForm getResultForm = (GetResultForm) form;// TODO Auto-generated method stub
		String result = getResultForm.getResult();
		String moduleId = getResultForm.getModuleId();
		System.out.println(result);
		System.out.println(moduleId);
		List<List<String>> ne = new ArrayList<List<String>>();
		List<String> s1 = new ArrayList<String>();
		String[] list1= result.split("\\$");
		for(String temp:list1)
		{
			s1.add(temp);
			
		}
		ne.add(s1);
		QueryModuleResultService service = (QueryModuleResultService) getBean("QueryModuleResultService");
		List<String> moduleResult = service.getModuleResult(ne, moduleId);
		System.out.println(moduleResult);
		ActionForward forward = mapping.getInputForward();
		forward = mapping.findForward("suc");
		request.setAttribute("resultList", moduleResult);
		return forward;
	}
}