/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.fudan.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import edu.fudan.struts.form.SearchImgForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-27-2014
 * 
 * XDoclet definition:
 * @struts.action path="/searchImg" name="searchImgForm" input="/searchImg.jsp" scope="request" validate="true"
 */
public class SearchImgAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchImgForm searchImgForm = (SearchImgForm) form;// TODO Auto-generated method stub
		System.out.println("dsfsd");
		ActionForward forward = mapping.getInputForward();
		String filePath = searchImgForm.getFilepath();
		System.out.println(filePath);
		forward = mapping.findForward("suc");
		return forward;
	}
}